name: Deploy IoT stack to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (for SSH-agent)
        uses: actions/checkout@v3

      - name: Start the SSH-agent
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add VPS fingerprint
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.VPS_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy IoT stack via git pull
        run: |
          ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            set -e
            mkdir -p /var/www/1dv027/iot
            cd /var/www/1dv027/iot

            if [ ! -d ".git" ]; then
              git init
              git remote add origin git@github.com:MarkerAnn/1dv027_IoT_server.git
              git fetch origin
              git checkout -b main origin/main
            else
              git remote set-url origin git@github.com:MarkerAnn/1dv027_IoT_server.git
              git pull origin main
            fi

            docker compose pull
            docker compose down
            docker compose up -d
          EOF
